# MySQL database configuration
database:
  host: localhost # Hôte de la base de données
  port: 3306 # Port à utiliser
  database: gloire # Nom de la base de données
  username: minecraft
  password: minecraft

# Configuration timer
timer:
  schedule_check: 1200 # Nombre de ticks à chaque check du timer (1200 = 1 minute)

# Plugin configuration
config:
  gloire_base: 100 # Nombre de Gloire qu'un nouveau joueur obtient
  gloire_joueur: 1000 # Nombre de Gloire qu'un joueur obtient en tuant un autre joueur
  gloire_joueur_perdant: 850 # Nombre de Gloire qu'un joueur perd en se faisant tuer par un autre joueur
  # Mobs
  gloire_creeper: 3 # Nombre de Gloire obtenus en tuant un Creeper
  gloire_bat: 3
  gloire_blaze: 3
  gloire_cave_spider: 3
  gloire_chicken: 3
  gloire_cow: 3
  gloire_donkey: 3
  gloire_ender_dragon: 3
  gloire_enderman: 3
  gloire_endermite: 3
  gloire_evoker: 3
  gloire_ghast: 3
  gloire_giant: 3
  gloire_guardian: 3
  gloire_horse: 3
  gloire_iron_golem: 3
  gloire_llama: 3
  gloire_magma_cube: 3
  gloire_mushroom_cow: 3
  gloire_ocelot: 3
  gloire_parrot: 3
  gloire_pig: 3
  gloire_pig_zombie: 3
  gloire_polar_bear: 3
  gloire_rabbit: 3
  gloire_sheep: 3
  gloire_skulker: 3
  gloire_silverfish: 3
  gloire_skeleton: 3
  gloire_skeleton_horse: 3
  gloire_slime: 3
  gloire_snowman: 3
  gloire_spider: 3
  gloire_squid: 3
  gloire_stray: 3
  gloire_vex: 3
  gloire_villager: 3
  gloire_witch: 3
  gloire_wither: 3
  gloire_wither_skeleton: 3
  gloire_wolf: 3
  gloire_zombie: 3
  gloire_zombie_horse: 3
  gloire_zombie_villager: 3
  # Messages
  gagner_gloires: '&dPour gagner des points de Gloire, tues des mobs ou combats d''autres joueurs. Le nombre de Gloire que tu gagneras dépend de la difficulté de tes combats.'
  broadcast_reset: '&d[Gloire] Reset des points de Gloire'
  timer: '&d[Gloire] Temps restant : &f'
  gagner_points: '&d[Gloire] Vous avez gagné %s points de gloire'
  gloire: '&d[Gloire] Vous avez %s points de gloire'
  gloire_gagnant: '&d[Gloire] Vous avez gagné %s points de Gloire (%t% du gain total)'
  gloire_perdant: '&d[Gloire] Vous avez perdu %s points de Gloire'
  gloire_24h: '&d[Gloire] Vous avez déjà tué ce joueur dans les dernières 24 heures'
  permission: '&cVous n''avez pas la permission' # Si un joueur n'a pas la permission d'utiliser une commande

# Configuration des niveaux
levels:
  transcendant:
    prefix: '&c[TRANSCENDANT]&f'
  divin:
    prefix: '&d[DIVIN]&f'
  legendaire:
    prefix: '&5[LEGENDAIRE]&f'
  overlord:
    prefix: '&6[OVERLORD]&f'
  podium:
    value: 100000 # Nombre de gloire requis pour accéder aux rangs sans palier
  grand:
    value: 50000
    prefix: '&e[GRAND]&f'
  impitoyable:
    value: 25000
    prefix: '&3[IMPITOYABLE]&f'
  triomphant:
    value: 10000
    prefix: '&2[TRIOMPHANT]&f'
  temeraire:
    value: 5000
    prefix: '&a[TEMERAIRE]&f'
  aucun:
    prefix: ''
