database:
  host: localhost # Hôte de la base de données
  port: 3306 # Port à utiliser
  database: gloire # Nom de la base de données
  username: minecraft
  password: minecraft

config:
  gloire_base: 100 # Le nombre de Gloire qu'un nouveau joueur obtient
  gloire_creeper: 3 # Le nombre de Gloire obtenus en tuant un Creeper